### PR TITLE
Add GitHub Actions and deploy to SciJava Maven repository

### PR DESCRIPTION
**Pull request by imagejan**
Also clean up `pom.xml`:
* Remove `build` section
* Add `connection` and `developerConnection` to `scm` section

See also https://github.com/trackmate-sc/TrackMate-CTCRunner/issues/5#issuecomment-1621676329.

### CODE REVIEW

**Comment by ctrueden** [comment]
@xulman If you add me as temporary co-owner to the CellTrackingChallenge org, I'll add the deploy credentials, so that together with this PR we start getting JAR files on maven.scijava.org.

**Comment by xulman** [comment]
thanks @imagejan for the PR, and thanks @ctrueden for the offer

I have invited Curtis to become the admin of this repo, and once he uploads the credentials we could merge this PR

**Comment by xulman** [comment]
two things, however
- why I got no email about the existence of this PR? I have learned about it from other channels and only thanks to somebody else mentioning it... 

- I would like to keep the COMMITrev files part of my .jar files (which is the result of the bulky block in the plugin section), [you can read more about it here](https://github.com/mastodon-sc/mastodon-tomancak/pull/30), is it against any scijava etiquette to keep it there?

**Comment by ctrueden** [comment]
@xulman I got the invite for this repository, but not for the organization as a whole. Do you want the credentials added *only for this repo*, or would you potentially like to deploy builds from *other repos in this org* in the future?

If you want to deploy any other repos besides only this one, I will need an invite to the org as a whole.

> why I got no email about the existence of this PR?

Go to https://github.com/CellTrackingChallenge/measures and on the top right there are three buttons: Watch, Fork, and Star. Click the down arrow on Watch to change which notifications you get. To control which notifications send you email, visit https://github.com/settings/notifications.

**Comment by xulman** [comment]
thanks for the secrets and for the info about the watching.... I knew about all of that but what I was wrongly assuming that I am, as the creator of the repo, automatically receiving info about any repo traffic... but the Notification settings page as "Automatically watch repositories" option... (and an option to add more emails...) anyway, thanks again

**Comment by imagejan** [comment]
@xulman wrote:
> I would like to keep the COMMITrev files part of my .jar files (which is the result of the bulky block in the plugin section), https://github.com/mastodon-sc/mastodon-tomancak/pull/30, is it against any scijava etiquette to keep it there?

I removed the `<plugin>` section because I thought it was redundant with what's declared in `pom-scijava[-base]`, but I didn't read closely what it was doing. If you want to keep this functionality, I think there's no harm in keeping the section.

What's your opinion here, @ctrueden ?

**Comment by ctrueden** [comment]
My opinion is that the block is unnecessary, because you can already extract the exact commit hash of any SciJava JAR file by doing:
```
jar xf random.jar META-INF/MANIFEST.MF
grep Implementation-Build META-INF/MANIFEST.MF
rm -rf META-INF
```
Or if you have the `groovy` command line tool installed, via [this `jar-manifest` script](https://github.com/ctrueden/dotfiles/blob/3e90575f9e9272eb92587bfe45cde2e3de891a38/bin/jar-manifest).

But it's not against the rules or anything to have it... I just think it's redundant.

**Comment by xulman** [comment]
finally merged, I apologize for the delay :(

big thank you @imagejan and @ctrueden

**Pull request merged**
